version: '3.7'
services:
  client:
    build: client
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    container_name: client
    restart: always
    depends_on:
      - server
    environment:
      REACT_APP_SERVER_URL: http://localhost:8000

  server:
    container_name: server
    restart: always
    build: server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    ports:
      - 8000:8000
    environment:
      DB_URI: mongodb://mongo:27017/musaladb
      CLIENT_URL: http://localhost:3000

  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
